### ISSUE TITLE
Failing tests cause the extension to break

### ISSUE THREAD

**Issue by Wosi** [recca0120/vscode-phpunit#109]
Recently your awesome extension began to fail with this message whenever a testcase fails:

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '\\D:\projects\bloomkit\vendor\phpunit\phpunit\phpunit'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:147:14
    at FSReqCallback.oncomplete (fs.js:171:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: '\\\\D:\\projects\\bloomkit\\vendor\\phpunit\\phpunit\\phpunit'
}
[Info  - 20:45:22] Connection to server got closed. Server will restart.
```

I tried PhpUnit version 8.3 and 8.5. They do both show the same error. I'm on Windows 10 with VSCode 1.63.2

**Comment by silviojaeger** [comment]
+1

**Comment by cezaro** [comment]
I think author abandoned project :(

**Comment by lukewatts** [comment]
In the absence of a fix...

To get test-explorer to work again easily without having to restart vscode: 
1. Open the Command Pallette _(Win: Ctrl+Shift+P | Mac: Command+Shift+P)_
2. Type `reload`  (or `drw`)
3. Select `Developer: Reload Window`

This is the same as the Reload that happens when you install/uninstall an extension, so it will re-boot PHP Test Explorer

**Comment by recca0120** [comment]
try version 3.0
