### ISSUE TITLE
Spawn Error

### ISSUE THREAD

**Issue by bretterer** [recca0120/vscode-phpunit#175]
I am receiving this odd error showing up in the `Test Results` window when trying to run tests

```
Error: spawn --filter=^.*::(it_can_submit_an_order_with_pay_in_person)( with data set .*)?$ ENOENT
at ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:476:16)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I am not sure what is happening. Any assistance would be super helpful.

Debug Info:
PHP 8.3.0 (Using Laravel Herd)
PHPUnit 10.5.3
Node v21.4.0
NPM 10.2.4

VS Code:
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.1.0

**Comment by stephqui** [comment]
I've exactly the same problem.
I use VSCode, PHPUnit Test Explorer.

Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

 I want to do PHPUnit Test in VSCode windows (using PHP 8.3.1).
After multiple search on the net during 4 days, I have not found solutions.
What I did:
- re-install VS Code, 
- re-install PHPUnit v11 with composer,
- try different modules PhPUnit (Recca, Elon Mailn),
- try on another computer -> same problem.

So, it's not possible for me to do Unit Test with gaphic icons.
If someone can help Bretterer and Me... (are we only 2 guys having this pb on Earth ? :-)

**Comment by stephqui** [comment]
Ok, I've found what was causing my problem:
the VSCode extension "PHP Tools for Visual Studio Code" from DevSense was making an interacting with all the extensions like "phpunit test".
After completely uninstall VSCode AND the .code folder AND the "Appdata/Roaming/code", extension "PHPUNIT Test Explorer" start working, and I had no more "Error: spawn at ChildProcess._handle.onexit (node:internal/child_process:283:19) ...etc...".

I like the DevSense PHP extension, because there are a lot of functionnalities.
I hope this will help.
