### ISSUE TITLE
No tests have been found in this workspace yet

### ISSUE THREAD

**Issue by ili101** [recca0120/vscode-phpunit#205]
Hi, updated from 3.2.2 to 3.4.2.

`/srv/.vscode/settings.json`
``` json
{
    "phpunit.phpunit": "/srv/api/bin/phpunit",
    "phpunit.args": [
        "--configuration /srv/api/phpunit.xml.dist"
    ],
}
```

`/srv/api/phpunit.xml.dist`
``` xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://phpunit.readthedocs.io/en/latest/configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="tests/bootstrap.php"
         convertDeprecationsToExceptions="false"
         displayDetailsOnTestsThatTriggerWarnings="true"
>
    <php>
        <ini name="display_errors" value="1" />
        <ini name="error_reporting" value="-1" />
        <server name="APP_ENV" value="test" force="true" />
        <server name="SHELL_VERBOSITY" value="-1" />
        <server name="SYMFONY_PHPUNIT_REMOVE" value="" />
        <server name="SYMFONY_PHPUNIT_VERSION" value="9.6" />
    </php>

    <testsuites>
        <testsuite name="Project Test Suite">
            <directory>tests</directory>
        </testsuite>
    </testsuites>

    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">src</directory>
        </include>
    </coverage>

    <listeners>
        <listener class="Symfony\Bridge\PhpUnit\SymfonyTestsListener" />
    </listeners>

    <extensions>
    </extensions>
</phpunit>
```

Test file:
`/srv/api/tests/Api/FlowTest.php` (also tried to copy to `/srv/api/tests/FlowTest.php` or set `<directory>` to `/srv/api/tests/Api`)

Testing from terminal:
```
root ➜ / $ /srv/api/bin/phpunit --configuration /srv/api/phpunit.xml.dist
PHPUnit 10.5.24 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.13
Configuration: /srv/api/phpunit.xml.dist

SEEEE                                                               5 / 5 (100%)
...
```

**Comment by ili101** [comment]
Changed, still not detected.

**Comment by ghnp5** [comment]
Same.

This is my config:

		"phpunit.command": "node ./phpunit-wrapper.mjs",
		"phpunit.php": "",
		"phpunit.phpunit": "",

**Comment by ljubadr** [comment]
Since I updated to version `3.4.2` extension is not finding tests. Latest version which works for me is `3.3.9`

In my `phpunit.xml` I have

```xml
<testsuites>
    <testsuite name="Functional">
        <directory suffix="Test.php">packages/*/Tests</directory>
    </testsuite>
    ...
</testsuites>
```

If I replace `*` with specific folder 

```xml
<directory suffix="Test.php">packages/Package1/Tests</directory>
```

then it returns tests in versions after `3.3.9`

**Comment by dp-anto** [comment]
I have the same problem of this issue (which is the same of [2 weeks ago](https://github.com/recca0120/vscode-phpunit/issues/186))

**Comment by recca0120** [comment]
> Since I updated to version `3.4.2` extension is not finding tests. Latest version which works for me is `3.3.9`
> 
> In my `phpunit.xml` I have
> 
> ```
> <testsuites>
>     <testsuite name="Functional">
>         <directory suffix="Test.php">packages/*/Tests</directory>
>     </testsuite>
>     ...
> </testsuites>
> ```
> 
> If I replace `*` with specific folder
> 
> ```
> <directory suffix="Test.php">packages/Package1/Tests</directory>
> ```
> 
> then it returns tests in versions after `3.3.9`

Allow <directory suffix="Test.php">packages/*/Tests</directory> starting from version 3.4.4."

**Comment by recca0120** [comment]
The test files are not displayed; you can refer to #188 for more details.

**Comment by ili101** [comment]
It looks like my problem is that absolute paths are not working.
With my original config that worked before and works from terminal `/srv/api/bin/phpunit --configuration /srv/api/phpunit.xml.dist` the extension doesn't detect the XML:
```json
    "phpunit.args": [
        "--configuration", "/srv/api/phpunit.xml.dist"
    ],
```
if I change it to:
```json
    "phpunit.args": [
        "--configuration", "./api/phpunit.xml.dist"
    ],
```
Extention finds the XML (in `/srv/api/phpunit.xml.dist`) but PHPUnit looks for it in `/srv/api/api/phpunit.xml.dist`.

I think absolute paths need to be fixed so I can use my original config or something like what is suggested in the phpunit.args configuration example: 
``` json
    "phpunit.args": [
        "--configuration", "${workspaceFolder}/api/phpunit.xml.dist"
    ],
```

**Comment by ljubadr** [comment]
@recca0120 I just tested `3.4.4` that [you mentioned here](https://github.com/recca0120/vscode-phpunit/issues/205#issuecomment-2486313857) and it finds tests with `packages/*/Tests`

One thing that I noticed is that in this vscode extension `packages/*/Tests` is case sensitive so it won't match `packages/Package2/tests`

Current `phpunit.xml` config 

```xml
<directory suffix="Test.php">packages/*/Tests</directory>
```

will match both tests `packages/.../Tests` and `packages/.../tests`. I tested this by running

```bash
phpunit --list-tests
```

My `phpunit/phpunit` version is `9.6.10`

**Comment by ghnp5** [comment]
@recca0120 - thanks for your efforts!

But I just want to say that 3.4.7 is still broken for me 😊

**Comment by recca0120** [comment]
@ghnp5 you can install version > 3.4.9, maybe fix your problem.

**Comment by ghnp5** [comment]
Thanks. I tried 3.4.10, but it still doesn't find any tests. :(

What is the method the extension finds the Test php files? Is it in some config?

The reason I ask is because the settings I have are these:

	"phpunit.command": "node ./phpunit-wrapper.mjs",
	"phpunit.php": "",
	"phpunit.phpunit": "",

Which means I'm not passing any path/wildcard to say where the tests are.

The tests are inside a folder called `something/tests/`, with a file called `__phpunit.xml` with the configs for the tests.

So, unless the extension does a full scan to the whole repository to find the tests, I'm not seeing what other way the extension would know where the tests are.

Thanks!

**Comment by Etra-0** [comment]
I started experiencing this issue recently where the tests are not appearing in the testing section like they used to. I do remote development through SSH and docker/sail. Never had issues before, didn't change any config either.

**Comment by recca0120** [comment]
I find a bug on windows, try to fix this bug now

**Comment by ghnp5** [comment]
Thank you. The latest version is still not finding tests, for me :)

**Comment by ili101** [comment]
v3.4.14
This:
```json
    "phpunit.args": [
        "--configuration", "/srv/api/phpunit.xml.dist"
    ],
```
Is still misinterpreted by the extension as the same as this:
```json
    "phpunit.args": [
        "--configuration", "./srv/api/phpunit.xml.dist"
    ],
```
If the path starts with a "/" it is not relative but absolute.
Thank you!

**Comment by ili101** [comment]
> v3.4.14 This:
> 
> ```json
>     "phpunit.args": [
>         "--configuration", "/srv/api/phpunit.xml.dist"
>     ],
> ```
> 
> Is still misinterpreted by the extension as the same as this:
> 
> ```json
>     "phpunit.args": [
>         "--configuration", "./srv/api/phpunit.xml.dist"
>     ],
> ```
> 
> If the path starts with a "/" it is not relative but absolute. Thank you!

Hi @recca0120. Tested v3.4.15, the extension now finds the tests successfully! but when running, the path to PHPUnit gets changed unexpectedly removing part of it. Conf:
```json
    "phpunit.phpunit": "/srv/api/bin/phpunit",
    "phpunit.args": [
        "--configuration", "/srv/api/phpunit.xml.dist"
    ],
```
When clicking "Run tests":
```
php /srv/bin/phpunit --configuration=/srv/phpunit.xml.dist --colors=never --teamcity

❌ Could not open input file: /srv/bin/phpunit
```
As you can see the path from the config json "/srv/api/bin/phpunit" was changes to "/srv/bin/phpunit"
Thank you

**Comment by recca0120** [comment]
@ghnp5 

https://github.com/user-attachments/assets/5115d5dd-810e-40fe-bf7f-9dabe086e034

it work fine in windows 11, and I try to set 
```json
	"phpunit.php": "",
	"phpunit.phpunit": "",
        "phpunit.args": []
```
it work too.

you can clone this repo, and run debug mode to find where the problem is.

**Comment by recca0120** [comment]
@ili101 there are no reasons to change path, if you don't set any phpunit.paths.

**Comment by recca0120** [comment]
@ghnp5 

https://github.com/user-attachments/assets/92b28206-1a1a-4f91-b911-1a831aab69d3

like this video. you can print includePatterns, excludePatterns
if phpunit.xml not exists, default value would be

includePatterns = ['**/*.php']
excludePaterns = ['**/.git/**', '**/node_modules/**']

it is as same as https://github.com/recca0120/vscode-phpunit/blob/06d26a16e740bb482e696262afab5b24c4d49787/src/extension.ts#L230

**Comment by ghnp5** [comment]
> t work fine in windows 11,

Still not finding in the latest version, to me :(

I see it showed "1/1" first, but then right away said "No tests have been found".

I also tried to move the "tests" folder to the root of the repository, but it doesn't seem to help either.

Please answer these questions:

**What is the method the extension finds the Test php files? Is it in some config?**

**Does the extension do a full scan to the whole repository to find the tests?**

--

> you can clone this repo, and run debug mode to find where the problem is.

I'm not sure how to do that :(
I never developed extensions for VSCode.

--

Thank you for your last comment above (you posted it after I already typed the above 😄).

> if phpunit.xml not exists, default value would be

Ok - and if `phpunit.xml` exists, what exactly does it look for, inside that config?

What I have is a file called `__phpunit.xml`, with the underscores. Does the extension read that, or not because of the underscores?

If it defaults to:

> includePatterns = ['/*.php']

Then maybe that's the problem, because the Tests are not located in the root (`/`) of the repository?

Thank you!

**Comment by ili101** [comment]
> @ili101 there are no reasons to change path, if you don't set any phpunit.paths.

I don't understand. What should I change?

Let's pretend I work locally (I work in Doker Devcontainer but from the extension perspective it's identical to working locally).
My VSCode is open in `/srv` (so my `${workspaceFolder}` is "/srv").
I have the files in `/srv/api/bin/phpunit` and `/srv/api/phpunit.xml.dist`.
My settings.json:
```json
{
    "phpunit.phpunit": "/srv/api/bin/phpunit",
    "phpunit.args": [
        "--configuration", "/srv/api/phpunit.xml.dist"
    ]
}
```

When clicking "Run tests":
```
php /srv/bin/phpunit --configuration=/srv/phpunit.xml.dist --colors=never --teamcity

❌ Could not open input file: /srv/bin/phpunit
```

**Comment by ghnp5** [comment]
> I had "phpunit.paths" in my other (user) settings.json

Unfortunately, that's not my case :(
No PHPUnit configs in my user's settings.json.

3.4.16 still not working for me.

@recca0120 - if you can, please reply to my questions in my last comment above 😊 thank you very much.

**Comment by Etra-0** [comment]
Not sure about others but I was able to fix this in my Docker instance with this:
![image](https://github.com/user-attachments/assets/fb18f8ff-d759-424b-b0c3-4905baa7beb3)

**Comment by ghnp5** [comment]
Thanks @Etra-0 
I've just created a file `phpunit.xml` at the root of the repository, with the right (relative) path in `<directory>`, and then re-installed the latest version of the extension.
Still no tests found :(

**Comment by ljubadr** [comment]
@ghnp5 check if your tests folder case and phpunit.xml `<testsuite>` case matches. I [have issue with that](https://github.com/recca0120/vscode-phpunit/issues/205#issuecomment-2485374561) in newer versions of this extension. I was planning on opening a separate ticket for that

Can you share your `<testsuites>` section in `phpunit.xml` and content of `phpunit-wrapper.mjs`? 

If you run following command (edit to match your phpunit path)

```bash
phpunit --list-tests
```

do you see your tests in the list?

**Comment by ghnp5** [comment]
@ljubadr - the thing is that I didn't have a `phpunit.xml` file at all, and the tests were always found, up to `3.3.9`.

I only had a file called `__phpunit.xml` inside `projectname/tests/`, and the `.php` test files are there as well.
I just don't understand why did this behavior change, if it was working well before.

So, what I did today was to create an extra `phpunit.xml` file at the root, with this:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.1/phpunit.xsd"
	stopOnError="false"
	stopOnFailure="false"
	stopOnIncomplete="false"
	stopOnSkipped="false"
	colors="true"
	processIsolation="false"
	testdox="true"
	requireCoverageMetadata="false"
>
	<coverage/>
	<source>
		<include>
			<directory>projectname/</directory>
		</include>
	</source>
	<testsuites>
		<testsuite name="ProjectName Tests">
			<directory suffix=".php">projectname/tests/</directory>
		</testsuite>
	</testsuites>
</phpunit>
```

The case is correct, and there's no `*`.

I can't share the code of `phpunit-wrapper.mjs`, because it's proprietary, but what it does is fix the command parameters generated by the extension, in a way that works with docker, and then calls `docker compose run`, passing also `--configuration ....../__phpunit.xml`.

**Comment by ljubadr** [comment]
What I noticed just now after re-visiting version `3.3.9` is that extension was showing green testing buttons when I open specific file but it was not listing those tests in the side bar panel. In my case originally it might have been a bug that allowed extension to show the buttons in version `3.3.9`. I rarely use side bar panel and run tests directly from the file so I never really noticed. But I'll definitely open the ticket for `*` matching

Try to run `phpunit --list-tests` to see if your expected tests are being matched

Not sure what kind of docker setup you have but I use setup from [the docs](https://github.com/recca0120/vscode-phpunit?tab=readme-ov-file#docker) and it works well for me. My `settings.json`

```json
"phpunit.command": "docker exec -t <container-name> /bin/sh -c",
"phpunit.phpunit": "vendor/bin/phpunit",
"phpunit.php": "php",
"phpunit.args": [
    "-c",
    "phpunit.xml",
],
"phpunit.paths": {
    "${workspaceFolder}": "/var/www/html",
},
```

Note that I use `container-name` instead of recommended `container-id` because the name won't change

Not sure if something related to command changed and maybe your wrapper `phpunit-wrapper.mjs` is not working as expected 🤷

**Comment by ljubadr** [comment]
@ghnp5 with your custom setup you might need to clone and debug extension yourself since it's impossible to reproduce your for others

You would need to
- clone the repo
- npm install
- place breakpoint in `src/extension.ts:13` to see what is being matched
- F5 to start debugging
- open your project
- press button to reload tests so that it hits the breakpoint
- step debug `src/extension.ts`

I don't know much about this extension or developing vscode extensions generally, just basic stuff on how to debug issues. Maybe @recca0120 can help you out to narrow down the issue. Since this ticket is closed maybe you can open new issue?

**Comment by Etra-0** [comment]
For anyone who is still having issues, my previous method did not change anything.

I am using Docker for my Ubuntu EC2 instance for remote dev.

Right now, if I open up the Testing panel in VSCode, my PHPUnit tests are not loaded. BUT if I go to a specific folder with tests, then those specific tests populate in the panel. (But not all tests).

Before, it would always load all tests in the panel and I did not have to do to specific folders.

My config, paths, phpunit.xml, has not changed for years.

I noticed this started happening like about a month ago. I downgraded to version **3.2.2** and it works perfectly. The issue seems to be introduced from version **3.3.0** to latest version. (At least in my case)

**Comment by ljubadr** [comment]
I just tested `3.2.2` version and as @Etra-0 mentioned I see all the tests loaded in the testing panel. Whatever changed after that version broke loading tests in the testing panel for me too. And somehow until `3.3.9` I was still getting green buttons to run the tests even if they are not loaded in the panel

**Comment by ghnp5** [comment]
I really don't have the time to be debugging this, as I need to concentrate on other things.
I don't mind testing different configurations, but the problem of debugging is that sure, I can confirm it won't work by putting a breakpoint there. But then what? I'd need to spend time understanding why.

It was working up to 3.3.9, and as far as I know, no one was complaining that the tests were not loading.
So, the code that loads the tests just needs to be reverted to whatever method 3.3.9 was using.

Thanks for your efforts, @recca0120, they're really appreciated.

**Comment by Etra-0** [comment]
> I just tested `3.2.2` version and as @Etra-0 mentioned I see all the tests loaded in the testing panel. Whatever changed after that version broke loading tests in the testing panel for me too. And somehow until `3.3.9` I was still getting green buttons to run the tests even if they are not loaded in the panel

I forgot to mention but I am using PHPUnit version 11, PHP version 8.2. I upgraded to Laravel 11 a while back which upgraded PHUnit from 10 to 11 in my project. There were no issues. (IE I don't think it is a PHPUnit version issue).

So just leads me to believe it is an issue with the new update after a year of no changes. So I imagine it started there.

For now I am just going to stay on `3.2.2`. Maybe will look into it further..

**Comment by Etra-0** [comment]
> @ljubadr @ghnp5 @Etra-0
> 
> would you please follow those setps to help me confirm this issue
> 
>     1. clone this repo,
> 
>     2. npm ci
> 
>     3. open [extension.ts](https://github.com/recca0120/vscode-phpunit/blob/main/src/extension.ts#L12-L54)
> 
>     4. replace function getWorkspaceTestPatterns
> 
>     5. click debug and run extensions
> 
> 
> ```js
> async function getWorkspaceTestPatterns() {
>     if (!vscode.workspace.workspaceFolders) {
>         return [];
>     }
> 
>     const results = [];
>     for (const workspaceFolder of vscode.workspace.workspaceFolders) {
>         const includePatterns: string[] = [
>             '**/*.php'
>         ];
>         const excludePatterns = [
>             '**/.git/**', 
>             '**/node_modules/**',
>             '**/vendor/**',
>         ];
> 
>         results.push({
>             workspaceFolder,
>             pattern: new vscode.RelativePattern(workspaceFolder, `{${includePatterns.join(',')}}`),
>             exclude: new vscode.RelativePattern(workspaceFolder, `{${excludePatterns.join(',')}}`),
>         });
>     }
>     return results;
> }
> ```
> 
> you can follow this video
> 2024-12-04.9.37.59.mov
> 
> if all tests are loaded. I think your filesystem is case insensitive. maybe clone your project from git again. maybe fix your problem.

@recca0120 I have done your steps. FYI this was me just locally on my Windows system (which is case insensitive). All the tests were loaded. For my EC2 instance of course it is case-sensitive. 
![image](https://github.com/user-attachments/assets/686d7178-9744-44d8-b869-59ed4a1878ce)

**Comment by recca0120** [comment]
edit this file https://github.com/recca0120/vscode-phpunit/blob/main/.vscode/launch.json#L13-L14

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run Extension",
            "type": "extensionHost",
            "request": "launch",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "${workspaceFolder}/src/phpunit/__tests__/fixtures/phpunit-stub" // <-- your project path
            ],
            "outFiles": ["${workspaceFolder}/dist/**/*.js"],
            "preLaunchTask": "${defaultBuildTask}"
        },
        {
            "name": "Extension Tests",
            "type": "extensionHost",
            "request": "launch",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "--extensionTestsPath=${workspaceFolder}/out/test/suite/index"
            ],
            "outFiles": ["${workspaceFolder}/out/**/*.js", "${workspaceFolder}/dist/**/*.js"],
            "preLaunchTask": "tasks: watch-tests"
        }
    ]
}
```

**Comment by ljubadr** [comment]
@recca0120 thank you for the debugging steps and for looking into this

I use mac and it looks like it's case-insensitive

When I used code example from [your comment](https://github.com/recca0120/vscode-phpunit/issues/205#issuecomment-2517422589) I see that all the tests are being loaded

It looks like pattern that's passed from `phpunit.xml` to `vscode.workspace.findFiles` is not finding tests where folder case doesn't match. Looks like glob is case sensitive. Unfortunately I'm on some legacy project so some folders are `packages/*/tests` and some are `packages/*/Tests`. 

When I run phpunit from cli `phpunit --list-tests` then all tests are matched and it looks like the case doesn't matter and it's case insensitive

I don't know if maybe `vscode.workspace.findFiles` glob matching is limited to case sensitive. I found this discussion https://github.com/microsoft/vscode/issues/10633 which you might be able understand better than me 😄 

Currently I have this 

```xml
<directory suffix="Test.php">packages/*/Tests</directory>
```

and it doesn't find test files in `packages/*/tests`

But if I use this

```xml
<directory suffix="Test.php">packages/*/[Tt]ests</directory>
```

then all tests are matched both in cli and in extension. I found `[Tt]` example in the issue that I linked above [in this comment](https://github.com/microsoft/vscode/issues/10633#issuecomment-680928105)

When I debug `getWorkspaceTestPatterns()` and check `return results` I see that the pattern being used is

```
'{packages/*/[Tt]ests/**/*Test.php,tests/Feature/**/*Test.php,tests/Unit/**/*Test.php}'
```

So it looks like it's properly reading `phpunit.xml`

I'll go with `[Tt]` approach since that fixes my issue

----

@recca0120 in the CHANGELOG.md in this repo I saw that in [3.3.0](https://github.com/recca0120/vscode-phpunit/blob/main/CHANGELOG.md#330---2024-11-03) you added `support phpunit.xml` so that's probably why suddenly some people stopped seeing tests being loaded if they were missing `phpunit.xml` or they maybe had issues with  case sensitive matching...

**Comment by ljubadr** [comment]
@recca0120 one issue that I have with latest version `3.4.20` is that I had to remove `/bin/sh -c` from the `phpunit.command`. I saw change in [readme](https://github.com/recca0120/vscode-phpunit?tab=readme-ov-file#docker).

If I run tests with `/bin/sh -c` result just hangs forever and nothing happens

Old command is not working anymore

```json
"phpunit.command": "docker exec -t [container_name] /bin/sh -c",
```

This works

```json
"phpunit.command": "docker exec -t [container_name]",
```

It might be a breaking change? Sorry to add noise into this issue. Should I create new issue?

**Comment by recca0120** [comment]
> @recca0120 one issue that I have with latest version `3.4.20` is that I had to remove `/bin/sh -c` from the `phpunit.command`. I saw change in [readme](https://github.com/recca0120/vscode-phpunit?tab=readme-ov-file#docker).
> 
> If I run tests with `/bin/sh -c` result just hangs forever and nothing happens
> 
> Old command is not working anymore
> 
> ```json
> "phpunit.command": "docker exec -t [container_name] /bin/sh -c",
> ```
> 
> This works
> 
> ```json
> "phpunit.command": "docker exec -t [container_name]",
> ```
> 
> It might be a breaking change? Sorry to add noise into this issue. Should I create new issue?

create new issue is better

**Comment by recca0120** [comment]
@ghnp5 

The path rules are as follows:

- If phpunit.xml does not exist, the pattern will be **/*.php.
- If phpunit.xml exists, the pattern will be read from the test suites.
- If your phpunit.xml file is named __phpunit.xml, you must set phpunit.args = ['-c', '__phpunit.xml'].

However, I found some issues on Windows.

1. On Windows, the filesystem is case-insensitive, but `vscode.workspace.findFiles` is case-sensitive. You can see more details in [this commit].(https://github.com/recca0120/vscode-phpunit/issues/205#issuecomment-2518743921)

2. In VS Code, a path can have various patterns, such as:
- C:\Users\recca0120
- \Users\recca0120
- file:///c:/Users/recca0120
- file:///Users/recca0120

The issues mentioned above have been fixed. Version 3.4.24 might work in your case.

Since I use a Mac, it’s challenging for me to identify all possible patterns on Windows.
If you still encounter this problem, I’ll need more details to locate the root cause.

**Comment by ghnp5** [comment]
Thank you @recca0120 , for explaining the rules and the issues fixed.

> If your phpunit.xml file is named __phpunit.xml, you must set phpunit.args = ['-c', '__phpunit.xml'].

I don't want the file `__phpunit.xml` to be read by the extension, because the configs there are specifically to make it work well under the Docker container, which mounts from `projectname/tests/`. (and the xml file is inside there, too)

I have tried to put a separate `phpunit.xml` file at the root of the repository, with the path pointing to `projectname/tests/`, but it didn't resolve the problem.

> If phpunit.xml does not exist, the pattern will be `**/*.php`.

That seems correct, and in that case, it should be finding the files under `projectname/tests/`.

However, even with the latest version (v3.4.25), it's still not finding any tests.

This is with and without the `phpunit.xml` file at the root of the repository. Both ways don't work.

Going back to v3.3.9 resolves the problem.

![image](https://github.com/user-attachments/assets/cbf3c04a-3e18-4b08-8ac0-e5b4f4a66add)

![image](https://github.com/user-attachments/assets/5eb0cac9-3c7c-4f32-b330-45fd4affa783)

**Comment by ghnp5** [comment]
I cloned the repo, ran `npm ci`, and I pressed Debug.

But how do I debug this extension against the workspace of my own repository?

Also, when I pressed Debug, I got this alert:

![image](https://github.com/user-attachments/assets/6fdc2926-3325-4d76-98ba-7f34cbf758e9)

**Comment by ljubadr** [comment]
@ghnp5 you can click `Remember my choice for this task` and then `Debug Anyway`

Once new editor window opens you can then change opened folder to your project

I use `cmd+shift+p` (`ctrl+shift+p` on windows) and then select `File: Open Recent` and select my project folder from there

You can place the breakpoint and then re-trigger logic to find tests by running `PHPUnit: Reload tests` or opening the sidebar and Testing panel and then clicking on reload icon on the top

**Comment by ghnp5** [comment]
Thanks very much.
I did that now, and I was able to debug.

However, I didn't conclude much...

`getWorkspaceTestPatterns()` correctly goes through the 3 directories of the workspace, and for each, it doesn't find `phpunit.xml`, so it sets each to:

```
include => pattern = '{**/*.php}'
exclude => pattern = '{**/.git/**,**/node_modules/**,vendor/**/*}'
```

These are sent to `findInitialFiles()`.

Every single file .php file is listed in the `files` array of the Promise's `.then()`, including the Tests, and adds all them to `testCollection`.

On line 81, after `findInitialFiles()` ran, I had a look at `testCollection`.

1) `_workspaces` seems to have 2 items, one being `\`, and another being one of the other secondary folders. I would expect 3 folders to be there, since the workspace settings has 3 folders listed (and the 3 were iterated in `getWorkspaceTestPatterns()`), but it's not.

2) `phpUnitXML` contains `_file = ''`, and `_root = '<the secondary directory that is in _workspaces>'

3) `testItems` seems to contain the same items as `_workspaces`

4) I couldn't find a way to list the items of the collection itself, or at least see the size of the collection.

I couldn't find in the code where does it decide whether a PHP file is a Test or not.

**Comment by recca0120** [comment]
> Thanks very much. I did that now, and I was able to debug.
> 
> However, I didn't conclude much...
> 
> `getWorkspaceTestPatterns()` correctly goes through the 3 directories of the workspace, and for each, it doesn't find `phpunit.xml`, so it sets each to:
> 
> ```
> include => pattern = '{**/*.php}'
> exclude => pattern = '{**/.git/**,**/node_modules/**,vendor/**/*}'
> ```
> 
> These are sent to `findInitialFiles()`.
> 
> Every single file .php file is listed in the `files` array of the Promise's `.then()`, including the Tests, and adds all them to `testCollection`.
> 
> On line 81, after `findInitialFiles()` ran, I had a look at `testCollection`.
> 
> 1. `_workspaces` seems to have 2 items, one being `\`, and another being one of the other secondary folders. I would expect 3 folders to be there, since the workspace settings has 3 folders listed (and the 3 were iterated in `getWorkspaceTestPatterns()`), but it's not.
> 2. `phpUnitXML` contains `_file = ''`, and `_root = ''
> 3. `testItems` seems to contain the same items as `_workspaces`
> 4. I couldn't find a way to list the items of the collection itself, or at least see the size of the collection.
> 
> I couldn't find in the code where does it decide whether a PHP file is a Test or not.

I haven't implemented the Multi-root Workspaces feature yet. You can create an issue for this.

old version work perfectly, because it doesn't switch tests list when workspace change.
keep workspace only has one folder. I think it can work.

**Comment by ghnp5** [comment]
Thank you @recca0120 

Just created #224

Many thanks.

**Comment by Etra-0** [comment]
@ghnp5 @recca0120 Thanks. Latest version is working for me.
