### ISSUE TITLE
Cannot run all tests 

### ISSUE THREAD

**Issue by s-burtonshaw** [recca0120/vscode-phpunit#42]
Running all tests doesn't seem work to work. The test explorer output just shows phpUnit usage:

> PHPUnit 4.8.36 by Sebastian Bergmann and contributors.
> 
> Usage: phpunit [options] UnitTest [UnitTest.php]
>        phpunit [options] <directory>
> 
> Code Coverage Options:
> ...

The diagnostics log shows it's because PHPUnit is being run with no arguments when it expects at least one:

>[2019-10-16 15:13:01.099] [INFO] { title: 'PHPUnit LSP',
>
>  command: 'c:\\<some path\>\\vendor\\bin\\phpunit.bat',
>   arguments: [] }

Should "Run all tests" instead pass the current dir e.g: `c:\<some path>\vendor\bin\phpunit.bat' .`?

**Comment by recca0120** [comment]
I'm rewriting this project now, it will fix this issue at next version

**Comment by sfsccn** [comment]
A possible workaround may be to create `phpunit.xml` so that all tests are run when no arguments are passed to the `phpunit` command.

My environment:

**OS**: Ubuntu Server 18.04.3
**php**: 7.2.24
**phpunit**: 8.5.2

Here, `phpunit` was installed locally via `composer` 1.9.3, so the command is `./vendor/bin/phpunit`. After installing the extension, in the Test Explorer I could run tests individually or run all tests in an entire class. But clicking "run all tests" (the "play" button) results in all tests appearing as failed in the Test Explorer, and the output just shows `phpunit` usage as described above.

The workaround is to create `phpunit.xml` as follows:

```xml
<phpunit bootstrap="vendor/autoload.php">
    <testsuites>
        <testsuite name="mySuite">
            <directory>tests</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

The command line effect is that `./vendor/bin/phpunit` with no arguments runs all the tests. And the "run all tests" button now seems to work in the Test Explorer: all tests show as passed.

**Comment by miku3920** [comment]
I have same problem.

Windows 10 20H2
PHP 7.3.10
PHPUnit 9.5.2

**Comment by recca0120** [comment]
yes! it needs phpunit.xml to run all tests!

try version 3.0, some problems are resolved
